# This is a demo workflow for the deploy step

name: deploy

on:
  workflow_dispatch:
    inputs:
      aviator_deployment_id:
        description: "Database ID of deployment"
        required: false
        type: string
      aviator_release_cut_commit_hash:
        description: "Commit SHA to be deployed"
        required: false
        type: string
      aviator_release_candidate_version:
        description: "Version to deploy"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print the inputs
        run: |
          echo "Inputs:"
          echo "aviator_deployment_id=${{ inputs.aviator_deployment_id }}"
          echo "aviator_release_cut_commit_hash=${{ inputs.aviator_release_cut_commit_hash }}"
          echo "aviator_release_candidate_version=${{ inputs.aviator_release_candidate_version }}"

      # Checks-out your repository
      - uses: actions/checkout@v4
        with:
          ref: "${{ inputs.aviator_release_candidate_version }}"
          lfs: true
          submodules: 'recursive'
          
      - name: Sync IDs via Aviator API
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.aviator.co/api/v1/sync-deploy-github-action'
          method: 'POST'
          bearerToken: ${{ secrets.AVIATOR_API_TOKEN }}
          data: '{"deployment_id": "${{ inputs.aviator_deployment_id }}", "workflow_run_id": "${{ github.run_id }}"}'
  
      - name: Wait until canceled
        shell: bash
        run: |
          sleep 60
